# Create the directories
mkdir .github\workflows -Force

# Create the CI file
@"
name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build frontend
      run: npx nx build frontend
"@ | Out-File -FilePath .github\workflows\ci.yml -Encoding utf8

# Commit and push
git add .github
git commit -m "fix: add proper CI workflow for Nx"
git push
